import 'package:carely/utils/logger_config.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class UserData {
  final String id;
  final String name;
  final String jobType;
  final double distance;
  final String togetherTime;
  final Map<String, String> skills;
  final LatLng location;
  final int? age;
  final String? story;
  final List<Map<String, String>>? companions;

  UserData({
    required this.id,
    required this.name,
    required this.jobType,
    required this.distance,
    required this.togetherTime,
    required this.skills,
    required this.location,
    this.age,
    this.story,
    this.companions,
  });

  String get profileImagePath => 'assets/images/$jobType/profile/$id.svg';
  String get squareProfileImagePath =>
      'assets/images/$jobType/profile_square/$id.svg';

  /// skillKey에 해당하는 skill 이미지 경로 반환
  String getSkillImagePath(String skillKey) {
    final path = 'assets/images/$jobType/skills/$skillKey.png';
    logger.i('스킬 이미지 경로 요청: $path');
    return path;
  }

  String get skillImagePath => 'assets/images/$jobType/skills/$id.png';

  static String convertSkillLevel(String jobType, String skillLevel) {
    if (jobType == 'family') {
      switch (skillLevel) {
        case 'LOW':
          return '도움 필요';
        case 'MIDDLE':
          return '서투름';
        case 'HIGH':
          return '준수함';
        default:
          return '알 수 없음';
      }
    } else {
      switch (skillLevel) {
        case 'LOW':
          return '하급';
        case 'MIDDLE':
          return '중급';
        case 'HIGH':
          return '상급';
        default:
          return '알 수 없음';
      }
    }
  }
}

final List<UserData> dummyUsers = [
  UserData(
    id: '1',
    name: '이상덕',
    jobType: 'family',
    distance: 0.7,
    togetherTime: '3시간 20분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'HIGH'),
      'meal': UserData.convertSkillLevel('family', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('family', 'HIGH'),
      'bath': UserData.convertSkillLevel('family', 'LOW'),
      'walk': UserData.convertSkillLevel('family', 'MIDDLE'),
    },
    location: LatLng(37.5865, 126.9980),
    age: 67,
    story:
        '안녕하세요, 이상덕입니다. 가족을 돌보는 일에 최선을 다하고 있습니다. 도움이 필요하시면 언제든지 연락주세요. 함께 어려움을 나누고 싶습니다. 따뜻한 마음으로 서로에게 힘이 되어주는 관계를 만들어가고 싶습니다. 잘 부탁드립니다.',
    companions: [
      {'name': '박서준', 'date': '2024.05.10', 'msg': '세심한 배려에 감동했습니다. 정말 감사합니다.'},
      {
        'name': '김민경',
        'date': '2024.04.22',
        'msg': '정말 큰 도움이 되었어요, 감사합니다! 다음에 또 뵙고 싶네요.',
      },
      {'name': '이영희', 'date': '2024.03.15', 'msg': '항상 친절하게 대해주셔서 편안했습니다.'},
    ],
  ),
  UserData(
    id: '2',
    name: '박지민',
    jobType: 'volunteer',
    distance: 1.2,
    togetherTime: '5시간 10분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'meal': UserData.convertSkillLevel('volunteer', 'LOW'),
      'toilet': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'walk': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
    },
    location: LatLng(37.5441, 126.9555),
    age: 28,
    story:
        '자원봉사자 박지민입니다. 따뜻한 마음으로 봉사활동에 참여하고 있습니다. 작은 도움이라도 드릴 수 있다면 기쁩니다. 함께하는 세상을 만들어가요. 저의 작은 손길이 필요한 곳에 닿기를 바랍니다.',
    companions: [
      {
        'name': '이수현',
        'date': '2024.05.01',
        'msg': '친절하게 대해주셔서 감사합니다. 봉사자님의 따뜻한 마음에 감동했어요.',
      },
      {'name': '강지훈', 'date': '2024.04.10', 'msg': '짧은 시간이었지만 많은 도움을 받았습니다.'},
    ],
  ),
  UserData(
    id: '3',
    name: '정수연',
    jobType: 'caregiver',
    distance: 0.5,
    togetherTime: '2시간 45분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('caregiver', 'LOW'),
      'toilet': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'bath': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'walk': UserData.convertSkillLevel('caregiver', 'HIGH'),
    },
    location: LatLng(37.5878, 126.9974),
    age: 45,
    story:
        '전문 요양보호사 정수연입니다. 다년간의 경험과 전문 지식을 바탕으로 어르신들을 정성껏 모시고 있습니다. 믿고 맡겨주시면 최선을 다하겠습니다. 어르신들의 편안하고 행복한 하루를 위해 노력합니다.',
    companions: [
      {
        'name': '최현우',
        'date': '2024.03.15',
        'msg': '전문적인 케어 감사합니다. 덕분에 안심할 수 있었어요.',
      },
      {
        'name': '윤지아',
        'date': '2024.02.20',
        'msg': '덕분에 안심하고 일할 수 있었어요. 정말 든든합니다.',
      },
      {
        'name': '강태민',
        'date': '2024.01.10',
        'msg': '항상 밝게 대해주셔서 좋아요. 기분까지 좋아집니다.',
      },
      {'name': '배수지', 'date': '2023.12.05', 'msg': '세심하게 신경 써주셔서 감사합니다.'},
    ],
  ),
  UserData(
    id: '4',
    name: '김민지',
    jobType: 'family',
    distance: 1.5,
    togetherTime: '4시간 50분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('family', 'HIGH'),
      'toilet': UserData.convertSkillLevel('family', 'LOW'),
      'bath': UserData.convertSkillLevel('family', 'MIDDLE'),
      'walk': UserData.convertSkillLevel('family', 'HIGH'),
    },
    location: LatLng(37.5900, 127.0000),
    age: 52,
    story: '가족을 사랑하는 마음으로 간병하고 있습니다.',
    companions: [],
  ),
  UserData(
    id: '5',
    name: '이준호',
    jobType: 'volunteer',
    distance: 2.0,
    togetherTime: '6시간 30분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'toilet': UserData.convertSkillLevel('volunteer', 'LOW'),
      'bath': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'walk': UserData.convertSkillLevel('volunteer', 'HIGH'),
    },
    location: LatLng(37.5920, 127.0020),
    age: 33,
    story: '봉사를 통해 함께 성장하고 싶습니다.',
    companions: [
      {'name': '송예나', 'date': '2024.04.05', 'msg': '시간 내주셔서 감사합니다.'},
    ],
  ),
  UserData(
    id: '6',
    name: '최수아',
    jobType: 'caregiver',
    distance: 0.3,
    togetherTime: '1시간 15분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'meal': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'bath': UserData.convertSkillLevel('caregiver', 'LOW'),
      'walk': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
    },
    location: LatLng(37.5885, 126.9995),
    age: 39,
    story: '진심을 담아 돌보겠습니다.',
    companions: [
      {'name': '김영철', 'date': '2024.05.18', 'msg': '꼼꼼하게 잘 챙겨주셔서 감사합니다.'},
    ],
  ),
  UserData(
    id: '7',
    name: '박영철',
    jobType: 'family',
    distance: 0.9,
    togetherTime: '2시간 10분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'LOW'),
      'meal': UserData.convertSkillLevel('family', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('family', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('family', 'HIGH'),
      'walk': UserData.convertSkillLevel('family', 'LOW'),
    },
    location: LatLng(37.5850, 126.9970),
  ),
  UserData(
    id: '8',
    name: '최유진',
    jobType: 'volunteer',
    distance: 2.5,
    togetherTime: '7시간 15분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'LOW'),
      'meal': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'bath': UserData.convertSkillLevel('volunteer', 'LOW'),
      'walk': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
    },
    location: LatLng(37.5930, 127.0030),
  ),
  UserData(
    id: '9',
    name: '김지훈',
    jobType: 'caregiver',
    distance: 1.3,
    togetherTime: '4시간 15분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'meal': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'toilet': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'walk': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
    },
    location: LatLng(37.5880, 127.0010),
  ),
  UserData(
    id: '10',
    name: '이수진',
    jobType: 'family',
    distance: 2.2,
    togetherTime: '3시간 45분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('family', 'HIGH'),
      'toilet': UserData.convertSkillLevel('family', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('family', 'LOW'),
      'walk': UserData.convertSkillLevel('family', 'HIGH'),
    },
    location: LatLng(37.5910, 127.0040),
  ),
  UserData(
    id: '11',
    name: '박준영',
    jobType: 'volunteer',
    distance: 1.7,
    togetherTime: '5시간 30분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'meal': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'bath': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'walk': UserData.convertSkillLevel('volunteer', 'HIGH'),
    },
    location: LatLng(37.5860, 127.0030),
  ),
  UserData(
    id: '12',
    name: '최미영',
    jobType: 'caregiver',
    distance: 0.8,
    togetherTime: '2시간 50분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'toilet': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'bath': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'walk': UserData.convertSkillLevel('caregiver', 'LOW'),
    },
    location: LatLng(37.5840, 126.9990),
  ),
  UserData(
    id: '13',
    name: '정민수',
    jobType: 'family',
    distance: 1.9,
    togetherTime: '4시간 20분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'HIGH'),
      'meal': UserData.convertSkillLevel('family', 'LOW'),
      'toilet': UserData.convertSkillLevel('family', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('family', 'HIGH'),
      'walk': UserData.convertSkillLevel('family', 'MIDDLE'),
    },
    location: LatLng(37.5930, 126.9980),
  ),
  UserData(
    id: '14',
    name: '김서연',
    jobType: 'volunteer',
    distance: 1.1,
    togetherTime: '3시간 15분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'toilet': UserData.convertSkillLevel('volunteer', 'LOW'),
      'bath': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'walk': UserData.convertSkillLevel('volunteer', 'HIGH'),
    },
    location: LatLng(37.5870, 127.0020),
  ),
  UserData(
    id: '15',
    name: '이동훈',
    jobType: 'caregiver',
    distance: 2.4,
    togetherTime: '6시간 10분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'meal': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'bath': UserData.convertSkillLevel('caregiver', 'LOW'),
      'walk': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
    },
    location: LatLng(37.5920, 127.0010),
  ),
  UserData(
    id: '16',
    name: '박지은',
    jobType: 'family',
    distance: 0.6,
    togetherTime: '2시간 30분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'LOW'),
      'meal': UserData.convertSkillLevel('family', 'HIGH'),
      'toilet': UserData.convertSkillLevel('family', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('family', 'HIGH'),
      'walk': UserData.convertSkillLevel('family', 'LOW'),
    },
    location: LatLng(37.5850, 127.0000),
  ),
  UserData(
    id: '17',
    name: '최준호',
    jobType: 'volunteer',
    distance: 1.4,
    togetherTime: '4시간 45분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'meal': UserData.convertSkillLevel('volunteer', 'LOW'),
      'toilet': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'walk': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
    },
    location: LatLng(37.5890, 127.0040),
  ),
  UserData(
    id: '18',
    name: '정수진',
    jobType: 'caregiver',
    distance: 2.1,
    togetherTime: '5시간 20분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'toilet': UserData.convertSkillLevel('caregiver', 'LOW'),
      'bath': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'walk': UserData.convertSkillLevel('caregiver', 'HIGH'),
    },
    location: LatLng(37.5910, 126.9990),
  ),
  UserData(
    id: '19',
    name: '김민준',
    jobType: 'family',
    distance: 1.6,
    togetherTime: '3시간 40분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'HIGH'),
      'meal': UserData.convertSkillLevel('family', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('family', 'HIGH'),
      'bath': UserData.convertSkillLevel('family', 'LOW'),
      'walk': UserData.convertSkillLevel('family', 'MIDDLE'),
    },
    location: LatLng(37.5880, 127.0030),
  ),
  UserData(
    id: '20',
    name: '이지원',
    jobType: 'volunteer',
    distance: 0.9,
    togetherTime: '2시간 55분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'toilet': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'walk': UserData.convertSkillLevel('volunteer', 'LOW'),
    },
    location: LatLng(37.5860, 127.0010),
  ),
  UserData(
    id: '21',
    name: '박서연',
    jobType: 'caregiver',
    distance: 2.3,
    togetherTime: '6시간 40분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'meal': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'bath': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'walk': UserData.convertSkillLevel('caregiver', 'HIGH'),
    },
    location: LatLng(37.5930, 127.0000),
  ),
  UserData(
    id: '22',
    name: '최민지',
    jobType: 'family',
    distance: 1.2,
    togetherTime: '3시간 50분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'LOW'),
      'meal': UserData.convertSkillLevel('family', 'HIGH'),
      'toilet': UserData.convertSkillLevel('family', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('family', 'HIGH'),
      'walk': UserData.convertSkillLevel('family', 'MIDDLE'),
    },
    location: LatLng(37.5870, 127.0040),
  ),
  UserData(
    id: '23',
    name: '정준영',
    jobType: 'volunteer',
    distance: 1.8,
    togetherTime: '5시간 15분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'meal': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'bath': UserData.convertSkillLevel('volunteer', 'LOW'),
      'walk': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
    },
    location: LatLng(37.5900, 127.0020),
  ),
  UserData(
    id: '24',
    name: '김지민',
    jobType: 'caregiver',
    distance: 0.7,
    togetherTime: '2시간 20분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'toilet': UserData.convertSkillLevel('caregiver', 'LOW'),
      'bath': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'walk': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
    },
    location: LatLng(37.5850, 127.0020),
  ),
  UserData(
    id: '25',
    name: '이수진',
    jobType: 'family',
    distance: 2.0,
    togetherTime: '4시간 10분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'HIGH'),
      'meal': UserData.convertSkillLevel('family', 'LOW'),
      'toilet': UserData.convertSkillLevel('family', 'HIGH'),
      'bath': UserData.convertSkillLevel('family', 'MIDDLE'),
      'walk': UserData.convertSkillLevel('family', 'HIGH'),
    },
    location: LatLng(37.5920, 127.0030),
  ),
  UserData(
    id: '26',
    name: '박지훈',
    jobType: 'volunteer',
    distance: 1.5,
    togetherTime: '3시간 30분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'toilet': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'walk': UserData.convertSkillLevel('volunteer', 'LOW'),
    },
    location: LatLng(37.5890, 127.0010),
  ),
  UserData(
    id: '27',
    name: '최서연',
    jobType: 'caregiver',
    distance: 2.5,
    togetherTime: '6시간 20분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'meal': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'bath': UserData.convertSkillLevel('caregiver', 'LOW'),
      'walk': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
    },
    location: LatLng(37.5940, 127.0010),
  ),
  UserData(
    id: '28',
    name: '정민준',
    jobType: 'family',
    distance: 1.0,
    togetherTime: '2시간 40분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'LOW'),
      'meal': UserData.convertSkillLevel('family', 'HIGH'),
      'toilet': UserData.convertSkillLevel('family', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('family', 'HIGH'),
      'walk': UserData.convertSkillLevel('family', 'MIDDLE'),
    },
    location: LatLng(37.5860, 127.0000),
  ),
  UserData(
    id: '29',
    name: '김서진',
    jobType: 'family',
    distance: 3.2,
    togetherTime: '4시간 10분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'HIGH'),
      'meal': UserData.convertSkillLevel('family', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('family', 'HIGH'),
      'bath': UserData.convertSkillLevel('family', 'LOW'),
      'walk': UserData.convertSkillLevel('family', 'MIDDLE'),
    },
    location: LatLng(37.4979, 127.0276),
  ),
  UserData(
    id: '30',
    name: '박지후',
    jobType: 'volunteer',
    distance: 2.8,
    togetherTime: '5시간 20분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'toilet': UserData.convertSkillLevel('volunteer', 'LOW'),
      'bath': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'walk': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
    },
    location: LatLng(37.5563, 126.9368),
  ),
  UserData(
    id: '31',
    name: '이하린',
    jobType: 'caregiver',
    distance: 4.1,
    togetherTime: '3시간 50분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'meal': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'bath': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'walk': UserData.convertSkillLevel('caregiver', 'LOW'),
    },
    location: LatLng(37.5407, 127.0707),
  ),
  UserData(
    id: '32',
    name: '정민재',
    jobType: 'family',
    distance: 5.0,
    togetherTime: '6시간 10분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('family', 'HIGH'),
      'toilet': UserData.convertSkillLevel('family', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('family', 'HIGH'),
      'walk': UserData.convertSkillLevel('family', 'LOW'),
    },
    location: LatLng(37.5133, 127.1002),
  ),
  UserData(
    id: '33',
    name: '최예준',
    jobType: 'volunteer',
    distance: 3.7,
    togetherTime: '2시간 40분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'meal': UserData.convertSkillLevel('volunteer', 'LOW'),
      'toilet': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'walk': UserData.convertSkillLevel('volunteer', 'HIGH'),
    },
    location: LatLng(37.5779, 126.8902),
  ),
  UserData(
    id: '34',
    name: '한지아',
    jobType: 'caregiver',
    distance: 2.9,
    togetherTime: '4시간 30분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'toilet': UserData.convertSkillLevel('caregiver', 'LOW'),
      'bath': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'walk': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
    },
    location: LatLng(37.5219, 126.9245),
  ),
  UserData(
    id: '35',
    name: '오지후',
    jobType: 'family',
    distance: 4.3,
    togetherTime: '5시간 50분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'HIGH'),
      'meal': UserData.convertSkillLevel('family', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('family', 'HIGH'),
      'bath': UserData.convertSkillLevel('family', 'MIDDLE'),
      'walk': UserData.convertSkillLevel('family', 'HIGH'),
    },
    location: LatLng(37.4812, 126.9527),
  ),
  UserData(
    id: '36',
    name: '서지안',
    jobType: 'volunteer',
    distance: 3.1,
    togetherTime: '3시간 30분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'toilet': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('volunteer', 'LOW'),
      'walk': UserData.convertSkillLevel('volunteer', 'HIGH'),
    },
    location: LatLng(37.5613, 127.0370),
  ),
  UserData(
    id: '37',
    name: '이준서',
    jobType: 'caregiver',
    distance: 2.7,
    togetherTime: '4시간 20분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'meal': UserData.convertSkillLevel('caregiver', 'LOW'),
      'toilet': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'walk': UserData.convertSkillLevel('caregiver', 'HIGH'),
    },
    location: LatLng(37.6380, 127.0257),
  ),
  UserData(
    id: '38',
    name: '김하윤',
    jobType: 'family',
    distance: 3.5,
    togetherTime: '2시간 50분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('family', 'HIGH'),
      'toilet': UserData.convertSkillLevel('family', 'LOW'),
      'bath': UserData.convertSkillLevel('family', 'HIGH'),
      'walk': UserData.convertSkillLevel('family', 'MIDDLE'),
    },
    location: LatLng(37.4850, 126.9015),
  ),
  UserData(
    id: '39',
    name: '박지민',
    jobType: 'volunteer',
    distance: 4.7,
    togetherTime: '6시간 40분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'meal': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'bath': UserData.convertSkillLevel('volunteer', 'LOW'),
      'walk': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
    },
    location: LatLng(37.6543, 127.0568),
  ),
  UserData(
    id: '40',
    name: '최서윤',
    jobType: 'caregiver',
    distance: 3.8,
    togetherTime: '5시간 10분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'toilet': UserData.convertSkillLevel('caregiver', 'LOW'),
      'bath': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'walk': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
    },
    location: LatLng(37.5311, 126.8636),
  ),
  UserData(
    id: '41',
    name: '이하준',
    jobType: 'family',
    distance: 2.6,
    togetherTime: '3시간 40분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'HIGH'),
      'meal': UserData.convertSkillLevel('family', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('family', 'HIGH'),
      'bath': UserData.convertSkillLevel('family', 'LOW'),
      'walk': UserData.convertSkillLevel('family', 'MIDDLE'),
    },
    location: LatLng(37.5385, 127.1238),
  ),
  UserData(
    id: '42',
    name: '정지우',
    jobType: 'volunteer',
    distance: 4.2,
    togetherTime: '2시간 30분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'toilet': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'walk': UserData.convertSkillLevel('volunteer', 'LOW'),
    },
    location: LatLng(37.4765, 126.9816),
  ),
  UserData(
    id: '43',
    name: '한서준',
    jobType: 'caregiver',
    distance: 3.3,
    togetherTime: '4시간 50분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'meal': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'bath': UserData.convertSkillLevel('caregiver', 'LOW'),
      'walk': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
    },
    location: LatLng(37.5495, 126.9137),
  ),
  UserData(
    id: '44',
    name: '이서연',
    jobType: 'family',
    distance: 2.4,
    togetherTime: '5시간 30분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'LOW'),
      'meal': UserData.convertSkillLevel('family', 'HIGH'),
      'toilet': UserData.convertSkillLevel('family', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('family', 'HIGH'),
      'walk': UserData.convertSkillLevel('family', 'MIDDLE'),
    },
    location: LatLng(37.5714, 127.0096),
  ),
  UserData(
    id: '45',
    name: '박하린',
    jobType: 'volunteer',
    distance: 3.6,
    togetherTime: '6시간 20분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'meal': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'bath': UserData.convertSkillLevel('volunteer', 'LOW'),
      'walk': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
    },
    location: LatLng(37.5345, 126.9940),
  ),
  UserData(
    id: '46',
    name: '최지안',
    jobType: 'caregiver',
    distance: 2.2,
    togetherTime: '3시간 10분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'toilet': UserData.convertSkillLevel('caregiver', 'LOW'),
      'bath': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'walk': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
    },
    location: LatLng(37.5547, 126.9706),
  ),
  UserData(
    id: '47',
    name: '이하린',
    jobType: 'family',
    distance: 4.8,
    togetherTime: '2시간 20분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'HIGH'),
      'meal': UserData.convertSkillLevel('family', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('family', 'HIGH'),
      'bath': UserData.convertSkillLevel('family', 'LOW'),
      'walk': UserData.convertSkillLevel('family', 'MIDDLE'),
    },
    location: LatLng(37.5894, 127.0576),
  ),
  UserData(
    id: '48',
    name: '정지호',
    jobType: 'volunteer',
    distance: 3.9,
    togetherTime: '4시간 40분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'toilet': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'walk': UserData.convertSkillLevel('volunteer', 'LOW'),
    },
    location: LatLng(37.6886, 127.0469),
  ),
  UserData(
    id: '49',
    name: '김지안',
    jobType: 'family',
    distance: 2.9,
    togetherTime: '3시간 30분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('family', 'HIGH'),
      'toilet': UserData.convertSkillLevel('family', 'LOW'),
      'bath': UserData.convertSkillLevel('family', 'HIGH'),
      'walk': UserData.convertSkillLevel('family', 'MIDDLE'),
    },
    location: LatLng(37.4650, 127.0150),
  ),
  UserData(
    id: '50',
    name: '박서진',
    jobType: 'volunteer',
    distance: 3.4,
    togetherTime: '4시간 50분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'meal': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'bath': UserData.convertSkillLevel('volunteer', 'LOW'),
      'walk': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
    },
    location: LatLng(37.4750, 126.9900),
  ),
  UserData(
    id: '51',
    name: '이하윤',
    jobType: 'caregiver',
    distance: 2.7,
    togetherTime: '5시간 10분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'toilet': UserData.convertSkillLevel('caregiver', 'LOW'),
      'bath': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'walk': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
    },
    location: LatLng(37.5250, 127.1050),
  ),
  UserData(
    id: '52',
    name: '정민서',
    jobType: 'family',
    distance: 3.1,
    togetherTime: '2시간 40분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'HIGH'),
      'meal': UserData.convertSkillLevel('family', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('family', 'HIGH'),
      'bath': UserData.convertSkillLevel('family', 'LOW'),
      'walk': UserData.convertSkillLevel('family', 'MIDDLE'),
    },
    location: LatLng(37.5550, 127.0250),
  ),
  UserData(
    id: '53',
    name: '최지후',
    jobType: 'volunteer',
    distance: 2.8,
    togetherTime: '3시간 20분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'toilet': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'walk': UserData.convertSkillLevel('volunteer', 'LOW'),
    },
    location: LatLng(37.5950, 127.0350),
  ),
  UserData(
    id: '54',
    name: '한지후',
    jobType: 'caregiver',
    distance: 3.6,
    togetherTime: '4시간 30분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'meal': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'bath': UserData.convertSkillLevel('caregiver', 'LOW'),
      'walk': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
    },
    location: LatLng(37.5050, 126.8850),
  ),
  UserData(
    id: '55',
    name: '이서준',
    jobType: 'family',
    distance: 2.5,
    togetherTime: '5시간 10분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'LOW'),
      'meal': UserData.convertSkillLevel('family', 'HIGH'),
      'toilet': UserData.convertSkillLevel('family', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('family', 'HIGH'),
      'walk': UserData.convertSkillLevel('family', 'MIDDLE'),
    },
    location: LatLng(37.5150, 127.0450),
  ),
  UserData(
    id: '56',
    name: '박지아',
    jobType: 'volunteer',
    distance: 3.7,
    togetherTime: '2시간 50분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'meal': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'bath': UserData.convertSkillLevel('volunteer', 'LOW'),
      'walk': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
    },
    location: LatLng(37.5350, 127.0550),
  ),
  UserData(
    id: '57',
    name: '이하린',
    jobType: 'caregiver',
    distance: 2.9,
    togetherTime: '4시간 40분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'toilet': UserData.convertSkillLevel('caregiver', 'LOW'),
      'bath': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'walk': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
    },
    location: LatLng(37.5450, 127.0650),
  ),
  UserData(
    id: '58',
    name: '정민아',
    jobType: 'family',
    distance: 3.3,
    togetherTime: '3시간 30분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'HIGH'),
      'meal': UserData.convertSkillLevel('family', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('family', 'HIGH'),
      'bath': UserData.convertSkillLevel('family', 'LOW'),
      'walk': UserData.convertSkillLevel('family', 'MIDDLE'),
    },
    location: LatLng(37.5550, 127.0750),
  ),
  UserData(
    id: '59',
    name: '최지민',
    jobType: 'volunteer',
    distance: 2.6,
    togetherTime: '4시간 20분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'toilet': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'walk': UserData.convertSkillLevel('volunteer', 'LOW'),
    },
    location: LatLng(37.5650, 127.0850),
  ),
  UserData(
    id: '60',
    name: '한서진',
    jobType: 'caregiver',
    distance: 3.5,
    togetherTime: '5시간 30분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'meal': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'bath': UserData.convertSkillLevel('caregiver', 'LOW'),
      'walk': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
    },
    location: LatLng(37.5750, 127.0950),
  ),
  UserData(
    id: '61',
    name: '이하윤',
    jobType: 'family',
    distance: 2.8,
    togetherTime: '2시간 40분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'LOW'),
      'meal': UserData.convertSkillLevel('family', 'HIGH'),
      'toilet': UserData.convertSkillLevel('family', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('family', 'HIGH'),
      'walk': UserData.convertSkillLevel('family', 'MIDDLE'),
    },
    location: LatLng(37.5850, 127.1050),
  ),
  UserData(
    id: '62',
    name: '박지후',
    jobType: 'volunteer',
    distance: 3.1,
    togetherTime: '3시간 10분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'meal': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'bath': UserData.convertSkillLevel('volunteer', 'LOW'),
      'walk': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
    },
    location: LatLng(37.5950, 127.1150),
  ),
  UserData(
    id: '63',
    name: '이하린',
    jobType: 'caregiver',
    distance: 2.7,
    togetherTime: '4시간 20분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'toilet': UserData.convertSkillLevel('caregiver', 'LOW'),
      'bath': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'walk': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
    },
    location: LatLng(37.6050, 127.1250),
  ),
  UserData(
    id: '64',
    name: '정민재',
    jobType: 'family',
    distance: 3.9,
    togetherTime: '5시간 10분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'HIGH'),
      'meal': UserData.convertSkillLevel('family', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('family', 'HIGH'),
      'bath': UserData.convertSkillLevel('family', 'LOW'),
      'walk': UserData.convertSkillLevel('family', 'MIDDLE'),
    },
    location: LatLng(37.6150, 127.1350),
  ),
  UserData(
    id: '65',
    name: '최예준',
    jobType: 'volunteer',
    distance: 2.5,
    togetherTime: '3시간 30분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'meal': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'toilet': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'walk': UserData.convertSkillLevel('volunteer', 'LOW'),
    },
    location: LatLng(37.6250, 127.1450),
  ),
  UserData(
    id: '66',
    name: '한지아',
    jobType: 'caregiver',
    distance: 3.7,
    togetherTime: '4시간 40분',
    skills: {
      'communication': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'meal': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('caregiver', 'HIGH'),
      'bath': UserData.convertSkillLevel('caregiver', 'LOW'),
      'walk': UserData.convertSkillLevel('caregiver', 'MIDDLE'),
    },
    location: LatLng(37.6350, 127.1550),
  ),
  UserData(
    id: '67',
    name: '오지후',
    jobType: 'family',
    distance: 2.6,
    togetherTime: '2시간 50분',
    skills: {
      'communication': UserData.convertSkillLevel('family', 'LOW'),
      'meal': UserData.convertSkillLevel('family', 'HIGH'),
      'toilet': UserData.convertSkillLevel('family', 'MIDDLE'),
      'bath': UserData.convertSkillLevel('family', 'HIGH'),
      'walk': UserData.convertSkillLevel('family', 'MIDDLE'),
    },
    location: LatLng(37.6450, 127.1650),
  ),
  UserData(
    id: '68',
    name: '서지안',
    jobType: 'volunteer',
    distance: 3.8,
    togetherTime: '3시간 20분',
    skills: {
      'communication': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'meal': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
      'toilet': UserData.convertSkillLevel('volunteer', 'HIGH'),
      'bath': UserData.convertSkillLevel('volunteer', 'LOW'),
      'walk': UserData.convertSkillLevel('volunteer', 'MIDDLE'),
    },
    location: LatLng(37.6550, 127.1750),
  ),
];
